---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  chartRef:
    kind: OCIRepository
    name: qbittorrent
  interval: 1h
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/buroa/qbittorrent-brr
              tag: 5.2.0@sha256:40474d9a3b65bc93998fd84827177072574576d5214bb0515d699694f99b51dd
            env:
              TZ: America/New_York
              QBT_WEBUI_PORT: &port 80
              QBT_TORRENTING_PORT: &torrentPort 48234
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 100m
              limits:
                memory: 32Gi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        forceRename: "{{ .Release.Name }}"
        primary: true
        ports:
          http:
            port: *port
      bittorrent:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.13.17.55
        externalTrafficPolicy: Cluster
        ports:
          bittorrent-tcp:
            port: *torrentPort
            protocol: TCP
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.dovis.me"
          - qbt.dovis.me
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    configMaps:
      config:
        data:
          .qbt.toml: |-
            [qbittorrent]
            addr = "http://localhost:80"
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
      config-file:
        type: configMap
        identifier: config
        globalMounts:
          - path: /config/.qbt.toml
            subPath: .qbt.toml
      incomplete:
        type: custom
        volumeSpec:
          ephemeral:
            volumeClaimTemplate:
              spec:
                accessModes: ["ReadWriteOnce"]
                resources:
                  requests:
                    storage: 1Mi # Ignored
                storageClassName: openebs-hostpath
                volumeMode: Filesystem
      media:
        type: nfs
        server: lil-nas.dovis.me
        path: /mnt/seagate-data
        globalMounts:
          - path: /data/torrents
            subPath: torrents
      tmp:
        type: emptyDir