# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:FDBgdmewdIoLu+fr7YS4z6ex+ntODDgvaje99bRResg=,iv:hgsDLClvqmuZoWAO+nPAdS1ZtMiIHjMLAehq2G/Wt0U=,tag:eqZpZsP0NGOpWeGJsSITCw==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRamhCUXdIZy92TzlqbG04
        czlNbzNhbEh2ajBqanYrVFRpeXpkTm5Ka0N3CjQxSStqcnI3Y0ZEOXlzYjVLZEpx
        bnFUSUN4cHJQZjlXdWUzNnYzTnZwVDAKLS0tIGRqRzdCMC9mZVZJZS9PNUhhYklM
        a1k4eEdRUUNCcmxpTjlIc3hYYnQwdlkK5BAy9oPWZjDSzQo9jZisHrRkWWHPZII9
        /RouZ106dYeKCFOFsAREmQtAY+rkb4pWwVG/qc1S74olcRrMuzNPcA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-30T03:28:09Z"
  mac: ENC[AES256_GCM,data:pv7+uLP7Jm8RgDzdOWN6VQ66KQfPFlRHXsWVuPyOgkN+O2vFUgAe52CAVqC2/XHXFIHVYyEbBFPKVCLLAWLaoyCMd+loBrerhG5/EIphSqwuAqKTAIKNbdds0vGe03R0qzIXIhohkixJw7zxvLmfIG6aAQuNsPb1ekmQSAp5Y/k=,iv:InmJrfNktjRmqz/3B4Eec7Swo5x1Rh1RdzLzyzVStWA=,tag:Cz+a2y3MGgYe7FPTDZ5b7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
