# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
  namespace: observability
stringData:
  UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:YilxfgoyT2B5LYXAcEGKPNmNstsqLHp/EFkjEfQygz4=,iv:tEBSWQG9QWy6gTzAip/djmG/bHm4jMzKyrT7TwsIEWs=,tag:cDARCjOt8P5OqaCFHstR6A==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtR1U3TXZSZXZGL3FoNDBl
        dGRnVVdaMVkrRGhOMUN4MmdML3VNcjdJeFhZCnZjVFc5bFZGVExiM2xLK250ZStZ
        M2JOMU5vS001VlFqR1o5amYxUzlVcEUKLS0tIElaZ01tRzhmSDdReDZUSjJuVVUy
        NHFvdnRZbkV3Ri81ZTViSEpia3pya2MKGD+Xy6BKkV26v7QuRXwSB77JgSgfv2WT
        cnfzPQMv889UFv7ch9Wg39wbB+5bjGtR3mjV+ZfzXy78Jl36HrCbVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T03:04:48Z"
  mac: ENC[AES256_GCM,data:+gNBbCFUpYF2GfPr4E8gibP3opkMW2scRExNEiEUtpGPlRWikc/zjDs2l664nXNyYdO3swNNnkLZwxH3wCGvBVRrjn2MjeohoBMIIjNFQoA7q3l0TwvjE2wM83072NzEqVIWL8Dk9L+6Fgf7y8i/smLylwLRxly/REmE5ID6RWw=,iv:6MOiys33GoVk3iuaz3f8ZAHDsN0vmxn+ngLWT7LKWnI=,tag:hFxuaC8vxJkmJ3ZW/29GIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
