# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: tautulli-secret
stringData:
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:NEjQZ+N2ue6vhIdmhToVTQcU53WT7KjOal7L8PL1GZw=,iv:SLTR+cYWclwuRXy9M8KBxJE6nd5tlIe0qv+Fzxlzwn0=,tag:cEOX4D2vq5rNwpaL7Nn+lQ==,type:str]
sops:
  age:
    - recipient: age185x77qt802d3arg3f5sdcl25ek4v3rmvtzjhe6pcezy72p0kv3asjfe20k
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WVFNa1pTYk5ETkZPaXVy
        Y0lCajJMU0hQUEVrVCtQZXcxVkxKQTNoZzJ3CjNOSXVQeXBtM2huOXBFb1VHZGJj
        NlZQOHpUcVovUUI2UmFXZlhOaXJhUGsKLS0tIElNWEVHOVVLRkRJN0xVVlYraFlD
        ZkhpZUxzQS8xamdvT1p2N2IyQ0lvN2sK8NERmx5c8Ch50ZWxUHttOgZkZOEX4KyC
        xsTtIPthQCujAu/tdnYPTk4jm74EP/GleP4W+KJiBjYtr72VPYRgsQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T20:35:45Z"
  mac: ENC[AES256_GCM,data:6nfnA/32PD72NIm6fgnhACkJM1M8FA1V5MsdF0oS+VXY4hPftZEb5Wzns1SLywpmDicCC8M1KTeC714c0icyDfxdFaswtO9nNJwNzFhN7Rc0dqGjZgJcCTk2IxbUzlU1Xy7zsaYh4BFUBtjpuUszKN2smzLw4JPdSpeLKdU0S24=,iv:2Mpab+me+/3oQeTpP6D6o+gXsjXEiIGERiNwco6xScs=,tag:AVTT5WugtbTTFWOsI7b5QQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
